sonar.projectKey=monority_devlens
sonar.organization=monority
sonar.host.url=https://sonarcloud.io
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info,coverage/lcov.info
sonar.sources=packages,apps
sonar.tests=packages,apps
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx
